In [24]:
# Importing Dependencies
import pandas as pd

In [25]:
# Reading in File
filePath = "../Data/ca_sites.csv"
f = pd.read_csv(filePath)
# Creating DataFrame
dfCASites = pd.DataFrame(f)

# Rename Column
dfCASites = dfCASites.rename(columns = {'City Name': 'City'}) 
# Drop Duplicates
dfCASites = dfCASites.drop_duplicates(subset=['City'])
dfCASites

,Defining Site,Latitude,Longitude,Elevation,Land Use,Location Setting,State Name,County Name,County Code,City,CBSA Name
0,06-001-0001,37.876870,-122.266913,15.0,RESIDENTIAL,URBAN AND CENTER CITY,California,Alameda,1,Berkeley,"San Francisco-Oakland-Hayward, CA"
1,06-001-0002,37.533243,-121.958813,22.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Fremont,"San Francisco-Oakland-Hayward, CA"
2,06-001-0003,37.684900,-121.765900,150.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Livermore,"San Francisco-Oakland-Hayward, CA"
3,06-001-0004,37.800484,-122.266358,38.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Oakland,"San Francisco-Oakland-Hayward, CA"
5,06-001-0006,37.710229,-122.116899,43.0,RESIDENTIAL,SUBURBAN,California,Alameda,1,Castro Valley,"San Francisco-Oakland-Hayward, CA"
...,...,...,...,...,...,...,...,...,...,...,...
1007,06-113-0005,38.682961,-121.766075,17.0,AGRICULTURAL,URBAN AND CENTER CITY,California,Yolo,113,Woodland,"Sacramento--Roseville--Arden-Arcade, CA"
1012,06-113-2001,38.571460,-121.525790,13.0,INDUSTRIAL,URBAN AND CENTER CITY,California,Yolo,113,West Sacramento,"Sacramento--Roseville--Arden-Arcade, CA"
1014,06-113-4001,38.896843,-121.967469,25.0,AGRICULTURAL,RURAL,California,Yolo,113,Dunnigan,"Sacramento--Roseville--Arden-Arcade, CA"
1015,06-115-0002,39.183505,-121.280513,268.0,AGRICULTURAL,RURAL,California,Yuba,115,Smartville,"Yuba City, CA"
1016,06-115-1001,39.010173,-121.426069,26.0,RESIDENTIAL,URBAN AND CENTER CITY,California,Yuba,115,Wheatland,"Yuba City, CA"

In [57]:
# Reading in File
filePath = "../Data/currentAQIData.csv"
f = pd.read_csv(filePath)
# Creating DataFrame
dfAQI = pd.DataFrame(f)

dfAQI['City'] = dfAQI['City'].str.strip()
dfAQI

,Unnamed: 0,City,Time,Date,Current AQI Value,Current Pollutant
0,0,Adelanto,7 PM PST,Mar 9,37,OZONE
1,1,Agoura Hills,7 PM PST,Mar 9,40,OZONE
2,2,Alameda,7 PM PST,Mar 9,37,OZONE
3,3,Albany,7 PM PST,Mar 9,37,OZONE
4,4,Alhambra,7 PM PST,Mar 9,37,OZONE
...,...,...,...,...,...,...
462,462,Yorba Linda,7 PM PST,Mar 9,38,OZONE
463,463,Yountville,7 PM PST,Mar 9,41,OZONE
464,464,Yreka,7 PM PST,Mar 9,31,OZONE
465,465,Yuba City,7 PM PST,Mar 9,33,OZONE
466,466,Yucaipa,7 PM PST,Mar 9,40,OZONE

In [61]:
dfMerge = pd.merge(dfCASites, dfAQI, how='left', on='City')

dfMerge = dfMerge.dropna()

dfMerge.head()

,Defining Site,Latitude,Longitude,Elevation,Land Use,Location Setting,State Name,County Name,County Code,City,CBSA Name,Unnamed: 0,Time,Date,Current AQI Value,Current Pollutant
0,06-001-0001,37.876870,-122.266913,15.0,RESIDENTIAL,URBAN AND CENTER CITY,California,Alameda,1,Berkeley,"San Francisco-Oakland-Hayward, CA",37.0,7 PM PST,Mar 9,37.0,OZONE
1,06-001-0002,37.533243,-121.958813,22.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Fremont,"San Francisco-Oakland-Hayward, CA",147.0,7 PM PST,Mar 9,38.0,OZONE
2,06-001-0003,37.684900,-121.765900,150.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Livermore,"San Francisco-Oakland-Hayward, CA",223.0,7 PM PST,Mar 9,36.0,OZONE
3,06-001-0004,37.800484,-122.266358,38.0,COMMERCIAL,URBAN AND CENTER CITY,California,Alameda,1,Oakland,"San Francisco-Oakland-Hayward, CA",282.0,7 PM PST,Mar 9,37.0,OZONE
6,06-001-0015,37.701222,-121.903019,101.0,RESIDENTIAL,SUBURBAN,California,Alameda,1,Pleasanton,"San Francisco-Oakland-Hayward, CA",314.0,7 PM PST,Mar 9,36.0,OZONE